name: Bump version of package

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: 'package to bump version'
      version:
        required: true
        description: 'new version for package'
      message:
        required: true
        description: 'commit msg'
        default: 'new upstream version'
  workflow_call:
    inputs:
      package:
        required: true
        type: string
        description: 'package to bump version'
      version:
        required: true
        type: string
        description: 'new version for package'
      message:
        required: true
        type: string
        description: 'commit msg'
        default: 'new upstream version'
    secrets:
      GH_APP_PRIVKEY:
        description: 'github app privkey'
        required: true

jobs:
  bumpver:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: gettoken
        with: 
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - uses: actions/checkout@v4
        with:
          repository: eweOS/packages
          ref: ${{ github.event.inputs.package }}
          path: repo
      - uses: actions/checkout@v4
        with:
          repository: eweOS/packages
          ref: _main
          path: meta
      - name: Set Git Info
        run: |
          cd repo
          git config --global user.name ${{ vars.GH_APP_NAME }}
          git config --global user.email ${{ vars.GH_APP_UID }}+${{ vars.GH_APP_NAME }}[bot]@users.noreply.github.com
      - name: Bump Package Version
        run: |
          cd repo
          bash ../meta/tools/bump_ver.sh ${{ github.event.inputs.version }}
      - name: Update Checksums
        run: >-
          docker run
          --rm
          -v $(pwd):/${{ github.workspace }}
          -w ${{ github.workspace }}
          ghcr.io/eweos/docker:master
          bash -c "
          pacman -Sy --noconfirm pacman-contrib &&
          cd repo &&
          updpkgsums
          "
      - name: Git Commit
        run: |
          cd repo
          git add PKGBUILD
          source PKGBUILD
          COMMITMSG="[$pkgname] $pkgver-$pkgrel: ${{ github.event.inputs.message }}"
          git commit -m "$COMMITMSG"
          echo COMMITMSG="$COMMITMSG" >> $GITHUB_ENV
          git reset --hard HEAD && git clean -df
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          path: repo
          token: ${{ steps.gettoken.outputs.token }}
          branch: bumppkgver/${{ github.event.inputs.package }}
          delete-branch: true
          branch-suffix: timestamp
          base: ${{ github.event.inputs.package }}
          push-to-fork: eweOS/.packages-auto
          title: ${{ env.COMMITMSG }}
          body: "generated by workflow bump_ver"
          labels: bump-pkgver,automated
