name: Check Update of Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      package:
        description: 'package to check'

jobs:
  updatecheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eweos/docker:updatecheck
    steps:
      - name: Restore cache
        run: |
          mkdir -p ~/.cache/archversion
          echo "{}" > ~/.cache/archversion/packages.cache
          wget https://raw.githubusercontent.com/eweOS/workflow/updatecheck/result.json -O ~/.cache/archversion/packages.cache
      - name: Update Repository
        run: pacman -Sy
      - name: Check for updates (all)
        if: ${{ github.event.inputs.package == '' }}
        run: eweversion check
      - name: Check for updates (single)
        if: ${{ github.event.inputs.package != '' }}
        run: eweversion check ${{ github.event.inputs.package }} 2> ~/err.log
      - name: Collect result
        run: |
          mkdir -p ~/checkresult
          cp ~/.cache/archversion/packages.cache ~/checkresult/result.json
      - name: Collect error result
        run: |
          grep "Upstream check failed" ~/err.log | grep "^ERROR: " | cut -f 4 -d ' ' | sed 's/:$//' | awk '{ print "\""$0"\""}' | jq -s '.' > ~/checkresult/failed.json
          grep "No pacman package found" ~/err.log | grep "^ERROR: " | cut -f 4 -d ' ' | sed 's/:$//' | awk '{ print "\""$0"\""}' | jq -s '.' > ~/checkresult/deprecated.json
      - name: Collect nodata result
        run: |
          pacman -S --noconfirm jq
          pacman -Slq main | xargs -I @ bash -c  "grep -q '\[@\]' ~/.config/archversion/packages.conf || echo @" | awk '{ print "\""$0"\""}' | jq -s '.' > ~/checkresult/nodata.json
      - name: Deploy result
        run: |
          pacman -S --noconfirm git 
          cd ~/checkresult
          git init
          git config --global user.name 'eweOS Update Checker'
          git config --global user.email 'nobody.noreply@ewe.moe'
          git add *.json
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/eweOS/workflow
          git commit -m "Update package list"
          git push github HEAD:updatecheck -f
