name: Check Pull Requests on OBS

on:
  repository_dispatch:
    types: [pr]

env:
  OSC_PASS: ${{ secrets.OSC_PASS }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Create check on PR
        id: createcheck
        env:
          GH_TOKEN: ${{ secrets.GH_APP_TOKEN }}
        run: |
          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f name='OBS Checks' \
            -f head_sha='${{ github.event.client_payload.prsha }}' \
            -f status='queued' \
            -f 'output[title]=Build on OBS Instance' \
            -f 'output[summary]=A *fancy* summary' \
            -f 'output[text]=More detailed Markdown **text**' \
            --jq '.id' \
            /repos/eweOS/packages/check-runs)
          echo "checkid=$CHECKID" >> $GITHUB_OUTPUT

