name: Check Pull Requests on OBS

on:
  repository_dispatch:
    types: [pr]

env:
  OSC_PASS: ${{ secrets.OSC_PASS }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: tibdex/github-app-token@v1
        id: gettoken
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Create check on PR
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ steps.gettoken.outputs.token }}
          name: Build package on OBS
          repo: eweOS/packages
          sha: ${{ github.event.client_payload.prsha }}
          status: queued
