name: Check Pull Requests

on:
  repository_dispatch:
    types: [pr]

jobs:
  buildpackage:
    strategy:
      matrix:
        arch: [amd64,arm64]
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: tibdex/github-app-token@v1
        id: gettoken
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Create check on PR
        uses: LouisBrunner/checks-action@v1.6.1
        id: getcheck
        with:
          token: ${{ steps.gettoken.outputs.token }}
          name: Build package on ${{ matrix.arch }}
          repo: eweOS/packages
          sha: ${{ github.event.client_payload.data.sha }}
          status: queued
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - uses: actions/checkout@v3
        with:
          repository: eweOS/packages
          ref: ${{ github.event.client_payload.data.sha }}
      - name: Flag progress
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: in_progress
      - name: Build in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ghcr.io/eweos/docker:buildenv \
            bash -c "set -euo pipefail && makepkg -s --noconfirm 2>&1 | tee build.log"
      - name: Conclude results
        if: always()
        run: |
          tail build.log -n 15 > build.tail.log
          ls ./*.pkg.* -l  | tee result.md
      - name: Flag results
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          conclusion: success
          output: |
            {"summary":"build successful"}
          output_text_description_file: result.md
      - name: Flag failure
        if: ${{ failure() }}
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          output: |
            {"summary":"build failed"}
          output_text_description_file: build.tail.log
          conclusion: failure
