name: Check Pull Requests

on:
  repository_dispatch:
    types: [pr]

jobs:
  checknamcap:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: tibdex/github-app-token@v1
        id: gettoken1
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: getjob
        with:
          github_token: ${{ steps.gettoken1.outputs.token }}
          job_name: ${{ github.job }}
      - name: Create check on PR
        uses: LouisBrunner/checks-action@v1.6.1
        id: getcheck
        with:
          token: ${{ steps.gettoken1.outputs.token }}
          name: Check PKGBUILD using namcap
          repo: eweOS/packages
          sha: ${{ github.event.client_payload.data.sha }}
          status: queued
          details_url: ${{ steps.getjob.outputs.html_url }}
      - uses: actions/checkout@v3
        with:
          repository: eweOS/packages
          ref: ${{ github.event.client_payload.data.sha }}
      - name: Flag progress
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken1.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: in_progress
          details_url: ${{ steps.getjob.outputs.html_url }}
      - name: Run namcap
        run: >-
          docker run
          --rm
          -v $(pwd):/${{ github.workspace }}
          -w ${{ github.workspace }}
          archlinux:latest
          bash -c "
          pacman -Sy --noconfirm namcap &&
          namcap ./PKGBUILD 2>&1 | tee namcap.log &&
          grep '' namcap.log  || echo namcap check successful, no error reported > namcap.log  &&
          set -euo pipefail &&
          grep -v ' E: ' namcap.log
          "
      - uses: tibdex/github-app-token@v1
        if: always()
        id: gettoken2
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Flag results
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken2.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          conclusion: success
          details_url: ${{ steps.getjob.outputs.html_url }}
          output: |
            {"summary":"check successful"}
          output_text_description_file: namcap.log
      - name: Flag failure
        if: ${{ failure() }}
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken2.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          details_url: ${{ steps.getjob.outputs.html_url }}
          output: |
            {"summary":"check failed"}
          output_text_description_file: namcap.log
          conclusion: failure

  buildpackage:
    strategy:
      matrix:
        arch: [amd64,arm64]
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: tibdex/github-app-token@v1
        id: gettoken1
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: getjob
        with:
          github_token: ${{ steps.gettoken1.outputs.token }}
          job_name: "buildpackage (${{ matrix.arch }})"
      - name: Create check on PR
        uses: LouisBrunner/checks-action@v1.6.1
        id: getcheck
        with:
          token: ${{ steps.gettoken1.outputs.token }}
          name: Build package on ${{ matrix.arch }}
          repo: eweOS/packages
          sha: ${{ github.event.client_payload.data.sha }}
          status: queued
          details_url: ${{ steps.getjob.outputs.html_url }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - uses: actions/checkout@v3
        with:
          repository: eweOS/packages
          ref: ${{ github.event.client_payload.data.sha }}
      - name: Flag progress
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken1.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: in_progress
          details_url: ${{ steps.getjob.outputs.html_url }}
      - name: Build in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ghcr.io/eweos/docker:buildenv \
            bash -c "pacman -Syu --noconfirm && set -euo pipefail && makepkg -s --noconfirm 2>&1 | tee build.log"
      - uses: tibdex/github-app-token@v1
        if: always()
        id: gettoken2
        with: 
          app_id: 337143
          private_key: ${{ secrets.GH_APP_PRIVKEY }}
      - name: Conclude results
        if: always()
        run: |
          tail build.log -n 15 > build.tail.log
          ls ./*.pkg.* -l  | tee result.md
      - name: Flag results
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken2.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          conclusion: success
          details_url: ${{ steps.getjob.outputs.html_url }}
          output: |
            {"summary":"build successful"}
          output_text_description_file: result.md
      - name: Flag failure
        if: ${{ failure() }}
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          repo: eweOS/packages
          token: ${{ steps.gettoken2.outputs.token }}
          check_id: ${{ steps.getcheck.outputs.check_id }}
          status: completed
          details_url: ${{ steps.getjob.outputs.html_url }}
          output: |
            {"summary":"build failed"}
          output_text_description_file: build.tail.log
          conclusion: failure
